Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnScriptStart", function() 
    Pickit.Start()
    end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnScriptStop", function() 
    Pickit.Stop()
    end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnPulse", function()
    Pickit.OnPulse()
  end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnGUIDraw", function()
    PickitSettings.DrawMainWindow()
  end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnRenderD2D", function()
    Pickit.OnRenderD2D()
  end)