Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnScriptStart", function() 
    AutoNPC.Start()
    end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnScriptStop", function() 
    AutoNPC.Stop()
    end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnPulse", function()
    AutoNPC.OnPulse()
  end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnGUIDraw", function()
    AutoNPCSettings.DrawMainWindow()
  end)
Infinity.Scripting.CurrentScript:RegisterCallback("Infinity.OnRenderD2D", function()
    AutoNPC.OnRenderD2D()
  end)